version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: evaluacion
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    # 🔥 ¡IMPORTANTE! No expongas el puerto si no lo necesitas fuera del contenedor
    # ports:
    #   - "3306:3306"

volumes:
  db_data:
